# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "greedy" 
  s.version = "0.0.0"

  s.required_rubygems_version = ">=1.3.7"
  s.authors = ["Jeremy Weiland"]
  s.date = %q{2010-07-22}
  s.summary = %q{Access a Google Reader stream}
  s.description = %q{With greedy, you can access and manipulate a stream of Google Reader entries via the API. Inspired by John Nunemaker's GoogleReader gem.}
  s.email = %q{jeremy6d@gmail.com}
  s.homepage = %q{http://github.com/jeremy6d/greedy}
  
  s.test_files = ["test/test_connection.rb", "test/test_entry.rb", 
                  "test/test_helper.rb", "test/test_stream.rb"]
  
  s.add_runtime_dependency('gdata', ["~>1.1.1"])
  s.add_runtime_dependency('nokogiri', ["~>1.4.2"])
  s.add_runtime_dependency('json', ["~>1.4.3"])
  s.add_runtime_dependency('cgi', ["~>1.1.1"])
  
  s.add_development_dependency('mocha', ["= 0.9.8"])
  s.add_development_dependency('shoulda', ["= 2.11.1"])
  s.add_development_dependency('jnunemaker-matchy', ["= 0.4.0"])
  
  s.require_path = "lib"
  s.files = Dir.glob("lib/**/*") + %w(LICENSE README.rdoc)
end

